### ISSUE TITLE
To-do list for Nicotine+ 3.2.0

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#1640]
Things that should (at least) be done for Nicotine+ 3.2.0:
- [x] https://github.com/nicotine-plus/nicotine-plus/pull/1639
- [x] https://github.com/nicotine-plus/nicotine-plus/pull/1587
- [x] https://github.com/nicotine-plus/nicotine-plus/discussions/1526#discussioncomment-1489941
- [x] https://github.com/nicotine-plus/nicotine-plus/discussions/1535#discussioncomment-1486907
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/1635
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/1660
- [x] SSL issue in macOS builds
- [x] Update release notes
- [x] Final testing

Other issues/requests may or may not be implemented for 3.2.0. I'm not sure how much time I'll have in the coming months, and I'd like to get a new release out the door sooner than later.

**Comment by mathiascode** [comment]
@slook I think it's a good time to stop making changes to translated strings now, to give our translators time to finish up things before the release. :)

**Comment by mathiascode** [comment]
Might make a minor exception or two for the statement above, but I'm looking at releasing 3.2.0 in early December.

**Comment by slook** [comment]
A Windows tester has a severe problem with the shares scanner, Scanning Shares bar never completes, no files shared. 

Currently investigating.
