### ISSUE TITLE
TODO-list for Nicotine+ 3.3.0

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#2260]
Nicotine+ 3.3.0 will be released mid to late 2023. This release will enable GTK 4 by default, revamp the command system, complete the Soulseek protocol implementation (distributed network), and introduce some new features.

In order to give a rough idea of where we currently stand, here's a list of required items before the release:

- [x] https://github.com/nicotine-plus/nicotine-plus/pull/2259
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/2025
- [x] Refactor widget color system to avoid GTK 4 deprecations, implement https://github.com/nicotine-plus/nicotine-plus/issues/2074
- [x] Minor string improvements
- [x] Enable GTK 4 by default on every platform
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/2141
- [x] Port all commands to the new plugin command system
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/994
- [x] Implement tray icon and notification support in GTK 4 on Windows (https://github.com/nicotine-plus/nicotine-plus/pull/2584)
- [x] https://github.com/nicotine-plus/nicotine-plus/issues/885
- [x] Resize cursor gets stuck on macOS
- [x] Waiting for uploads to finish before quitting can get stuck
- [x] Finalize strings
- [x] Update release notes
- [x] Update screenshots
- [ ] Final testing

Depending on how quickly the above list is completed, here are things that would be nice to have:

- Finish treeview rewrite
- https://github.com/nicotine-plus/nicotine-plus/issues/1651 (move now playing functionality to a plugin, incomplete branch: https://github.com/mathiascode/nicotine-plus/tree/nowplaying-plugin)
- https://github.com/nicotine-plus/nicotine-plus/issues/771 (use new scheduler system)
- https://github.com/nicotine-plus/nicotine-plus/issues/110
- Wishlist overhaul with filters
- Other popular requests, check which ones

**Comment by mathiascode** [comment]
I'll most likely not be able to work on Nicotine+ until June, so the new target for a 3.3.0 release is sometime during the second half of 2023.

**Comment by toineenzo** [comment]
I see "Enable GTK 4 by default on every platform" has already been implemented. But on the latest Linux Test build I see the following in the about window: 3.3.0.dev5, Python 3.6.9, GTK 3.22.30. Still GTK 3?

**Comment by mathiascode** [comment]
> I see "Enable GTK 4 by default on every platform" has already been implemented. But on the latest Linux Test build I see the following in the about window: 3.3.0.dev5, Python 3.6.9, GTK 3.22.30. Still GTK 3? I'm running the following docker container that I manually updated to the testing branch: https://hub.docker.com/r/sirjmann92/nicotineplus-proper

If GTK 4 isn't available on the system, GTK 3 will be used instead.

I don't recommend using GTK 4 with the Broadway backend (web interface) just yet, since it's very slow compared to GTK 3. Porting from GtkTreeView to GtkColumnView should hopefully improve this.

**Comment by toineenzo** [comment]
@mathiascode thank you for your clarification! Didn't know that.

**Comment by hboetes** [comment]
I just noticed someone downloading all the boring accompanying files of a dir, but not the rest of it, and then it struck me: I had just retagged/renamed the files in that folder but not yet rescanned the shares. But I didn't get an error message.

We should examine that.

**Comment by hboetes** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990852  🥳

**Comment by DeathStalker77** [comment]
Just mentioning that there IS still a significant performance/lag issue with a large amount of files queued - and it is proportional to the amount of files queued; the more files queued, the worse the performance (even when set as HIGH CPU Priority).  The orig SLSK ALSO has a similar issue.  This "lag time" - startup, switching tabs, etc - can last anywhere from a few minutes to several hours (~100k files queued).

**Comment by mathiascode** [comment]
As I've told you before, it's something I want to address eventually. I've run out of time to make any large changes for 3.3.0, so it will happen in a future release.

**Comment by DeathStalker77** [comment]
At this point, it's difficult to even identify what is queued from whom - opening the build from the 9th is now 7hs+ and I still can't do anything with the program.  It _did_ finish scanning the shared folder/files, but has been hung ever since.

**Comment by DeathStalker77** [comment]
@mathiascode - the new OCT-20 build seems MUCH more responsive!  Still hangs a bit when switching tabs or manually resuming, but at least it loads the original JSON queue now! :-)

Additionally, it appears to work fine even when using a different port than the port my VPN provides for Port Forwarding (which is an issue I'm suddenly having with the orig SLSK - posted about that on Reddit).

--- DS

**Comment by DeathStalker77** [comment]
So, for me, only BIG thing is to allow N+ to be able to use the SAME port/s as other apps - even the latest build gives the Port in use by another application message.

**Comment by slook** [comment]
Only one app can hold a port at a time. Even after an app closes, the OS might not release it until after some time.

**Comment by DeathStalker77** [comment]
That doesn't make sense - I have had multiple programs running with port forwarding before with no issues at all.

**Comment by DeathStalker77** [comment]
Also, it was working fine with the latest build from the 20th, until I shut down and re-started, now I have the same freezing that I did previously.

**Comment by DeathStalker77** [comment]
So, in the orig SLSK client, which uses 2 ports, when I set the Port in the client (where there is only 1 port option to set) to 1 port BELOW my OPEN PORT, and check ports, it shows the selected port as CLOSED, BUT it shows the 2nd port as OPEN.

Thus I am quite confused by the protocols that SLSK uses - as clearly the orig client CAN use the same port as another application.

**Comment by DeathStalker77** [comment]
@mathiascode - what about this?
https://learn.microsoft.com/en-us/dotnet/framework/wcf/feature-details/net-tcp-port-sharing

**Comment by mathiascode** [comment]
> So, in the orig SLSK client, which uses 2 ports, when I set the Port in the client (where there is only 1 port option to set) to 1 port BELOW my OPEN PORT, and check ports, it shows the selected port as CLOSED, BUT it shows the 2nd port as OPEN.
> 
> Thus I am quite confused by the protocols that SLSK uses - as clearly the orig client CAN use the same port as another application.

Have you verified that you're actually receiving incoming connections on that port in all the programs you use (not just indirect connections, where a connection is established by connecting to the other peer's port instead)?

**Comment by mathiascode** [comment]
Since you asked about why SoulseekQt uses two ports:

- The first port is for connections where plain protocol messages are sent (the original system since 2001).
- The second port is for newer connections (added in 2011) where protocol messages are obfuscated. To keep support for old Soulseek clients, this second port was added instead of replacing the original one. https://www.slsknet.org/news/node/253

Since P2P clients are no longer as popular/targeted as they used to be, no proof exists that ISPs throttled Soulseek connections, ports are in short supply, and all Soulseek clients support the original system, we decided not to use the new system (and it's effectively useless once everyone knows how it works).

**Comment by DeathStalker77** [comment]
While I can agree with you in that the P2P **CLIENTS** are no longer "main targets", I can assure you that USERS are still 100% "main targets" and that ALL filesharing software is used and monitored by "CopyWrong Cartels" & their ilk.  That is why I will NEVER do ANY sort of filesharing without a VPN.  Just because you haven't received a notice YET, does not mean you are never going to receive one, or are not "on the radar".  Consider it as just currently "dodging the bullets".

Ports, in & of themselves, are certainly NOT in "short supply" - there are 65,535 ports available, minus the well-known/well-used ports that total around 1024 +/-.

The "key" is going to be in making things so that the protocol CAN use the same port as another application.  The plain fact is, if people are NOT using VPNs, they _should_ be - and most people who do filesharing also use other software for it as well.

I see nothing wrong with not using the 2nd obfuscated port.

**Comment by mathiascode** [comment]
> While I can agree with you in that the P2P **CLIENTS** are no longer "main targets", I can assure you that USERS are still 100% "main targets" and that ALL filesharing software is used and monitored by "CopyWrong Cartels" & their ilk. That is why I will NEVER do ANY sort of filesharing without a VPN. Just because you haven't received a notice YET, does not mean you are never going to receive one, or are not "on the radar". Consider it as just currently "dodging the bullets".

Users are definitely targeted, but we're talking about throttling bandwidth by analyzing traffic and specifically detecting Soulseek protocol messages. I find it hard to believe that there wouldn't be some more generic/broad throttling in place.

In any case, a VPN would bypass protocol-specific throttling.

> Ports, in & of themselves, are certainly NOT in "short supply" - there are 65,535 ports available, minus the well-known/well-used ports that total around 1024 +/-.

Clarification, IPv4:port pairs exposed to the public. A clear example is your VPN that only allows you to forward a single port, or people behind CGNAT. The situation certainly won't improve, unless Nir adds support for IPv6.

**Comment by DeathStalker77** [comment]
Ok, agreed on both those points :-)  I do think the number of ISPs that still actively throttle any traffic is dwindling.  It's not the throttling of speed that I would be concerned with - hey, let's all be happy that we're getting stuff at all!  :-)  but rather the danger of "notifications".

**Comment by slook** [comment]
[Nicotine+ 3.3.0](https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.3.0) released on 1st February 2024.
