### ISSUE TITLE
Progress tracking: 2.1.0

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#504]
List of current things to do before releasing Nicotine+ 2.1.0:

- [x] Search -> Right Click -> Download folder(s) does nothing #574
- [x] Memory leak on Windows https://github.com/Nicotine-Plus/nicotine-plus/issues/520
- [x] Speed up pickle/shelf saving on Windows
- [x] Fix update checker in Windows builds
- [x] Remove (almost) all deprecated elements (mostly done in https://github.com/Nicotine-Plus/nicotine-plus/pull/500)
- [x] Update screenshots
- [x] Update changelog
- [x] Ensure nothing has broken since 2.0.1

**Comment by hboetes** [comment]
Almost there. :-)
