### ISSUE TITLE
Checklist for 3.0.0

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#989]
- [x] Investigate issue where public and buddy shares sometimes won't scan simultaneously
- [x] Test less common features of the client
- [x] Import translations from Launchpad
- [x] Update screenshots

Postponed for a future point release:
- https://github.com/Nicotine-Plus/nicotine-plus/issues/956
